### ISSUE TITLE
86BoxManager crashes after trying to delete a VM with read-only files in the directory

### ISSUE THREAD

**Issue by ATeamInc** [86Box/86BoxManager#56]
Attempting to delete a VM with some read-only or protected (in use) files in the directory causes the manager to crash. For instance, I installed Windows 3.11 and extracted the disk to a directory but deleting the VM yields a crash.
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'IO.SYS' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at _86boxManager.frmMain.VMRemove()
   at _86boxManager.frmMain.btnDelete_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![exception](https://user-images.githubusercontent.com/34858431/59975948-ffd93900-95c6-11e9-9f08-112d7e6a0794.PNG)

**Comment by daviunic** [comment]
I'll fix this so it's handled properly, but common sense also applies here - don't try to delete things that are in use or read-only.

**Comment by daviunic** [comment]
This has been fixed in version 1.5.1.
